# -*- coding: utf-8 -*-
"""Basic Rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPPxCJJ_HUrLqllwAxPgBK5rofPjRkx8
"""

!pip -q install transformers sentence-transformers faiss-cpu

import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from transformers import pipeline

docs = [
    "Hedge funds use investor capital to generate absolute returns regardless of market direction.",
    "Common strategies include long/short equity, global macro, statistical arbitrage, and event-driven investing.",
    "Risk management uses position sizing, stop losses, hedging, and diversification.",
    "An edge (alpha) can come from data advantages, execution speed, or better models.",
    "Long/short equity means buying undervalued stocks and shorting overvalued ones simultaneously.",
    "Global macro funds trade based on economic trends like interest rates, inflation, currencies, and geopolitics.",
    "Sharpe ratio measures risk-adjusted return. Higher Sharpe is better.",
    "Drawdown is the peak-to-trough loss in portfolio value. Funds try to minimize this.",
    "Beta is market exposure. Market-neutral funds keep beta close to 0.",
    "Alpha is return generated beyond market beta."
]

embedder = SentenceTransformer("all-MiniLM-L6-v2")
generator = pipeline("text-generation",model = "distilgpt2")

doc_vectors = embedder.encode(docs)
doc_vectors = np.array(doc_vectors).astype("float32")
print("Embedding Dimensions",doc_vectors.shape[1])

dim = doc_vectors.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(doc_vectors)
print("Total docs indexed",index.ntotal)

def retrieve(query,k=3):
  q_vec = embedder.encode([query])
  q_vec = np.array(q_vec).astype("float32")
  distances,indices = index.search(q_vec,k)
  retrieved_docs = [docs[i] for i in indices[0]]
  return retrieved_docs, distances[0], indices[0]

def gen_ans(query, retrieved_docs):
    context = "\n".join([f"- {d}" for d in retrieved_docs])

    prompt = f"""You are a hedge fund analyst at a top investment bank.
Answer ONLY using the context below. Keep it short and clear.

Context:
{context}

Question: {query}
Answer:"""

    out = generator(prompt, max_new_tokens=50, temperature=0.6, do_sample=True)
    return out[0]["generated_text"]

def rag(query, k=3):
    retrieved_docs, dist, idxs = retrieve(query, k)
    answer = gen_ans(query, retrieved_docs)
    return retrieved_docs, answer, dist

questions = [
    "How do hedge funds generate returns?",
    "What is portfolio drawdown?",
    "What strategies hedge funds use?",
    "Difference between alpha and beta?"
]
for q in questions:
    retrieved_docs, answer, _ = rag(q, k=3)
    print("\n--- QUERY:", q)
    print("Retrieved docs:", retrieved_docs)
    print("Generated answer:\n", answer)

